Repository elifesciences/elife-xpub, pull requests merged in 2018-07, with the labels that each got.

#277 test: AutoSave component
  app/components/submission/AutoSave.test.js
Labels: Epic1, Testing

#361 Scaling down the cluster out of hours
  .gitlab-ci.yml
Labels: Deployment

#387 Material icons
  app/components/ui/atoms/icons/index.js
  app/components/ui/atoms/icons/material/LICENSE-2.0.txt
  app/components/ui/atoms/icons/material/README.md
  app/components/ui/atoms/icons/material/Search.js
Labels: Client-Side

#391 fix(styleguide): remove material icons by themselves from the styleguide
  styleguide.config.js
Labels: Bug, Client-Side
