Repository elifesciences/elife-xpub, pull requests merged in 2019-06, with the labels that each got.

#2073 Remove unused texture from client folder
  client/texture/TextureContainer.js
  client/texture/TextureEditor.js
  client/texture/TextureEditor.md
  client/texture/index.js
  client/texture/package.json
  yarn.lock
Labels: Deployment

#2067 Add API testing utility
  tools/api-tests/.eslintrc
  tools/api-tests/.gitignore
  tools/api-tests/.nvmrc
  tools/api-tests/.prettierignore
  tools/api-tests/.prettierrc.yaml
  tools/api-tests/README.md
  tools/api-tests/codegen.yml
  tools/api-tests/package.json
  tools/api-tests/src/api-test/dashboard.test.ts
  tools/api-tests/src/api-test/manuscript.test.ts
  tools/api-tests/src/index.ts
  tools/api-tests/src/services/user.ts
  tools/api-tests/src/utils.ts
  tools/api-tests/src/xpub-api/dashboard.ts
  tools/api-tests/src/xpub-api/index.ts
  tools/api-tests/src/xpub-api/submission.ts
  tools/api-tests/tsconfig.json
  tools/api-tests/tsdoc.json
  tools/api-tests/yarn.lock
Labels: Server-Side

#2072 First step to improve dockerization
  Dockerfile-app
  Dockerfile-development
  Dockerfile-test_browser
  Jenkinsfile
  docker-compose.ci.yml
  scripts/local_pipeline.sh
Labels: Deployment

#2116 2086: swap new submission wizard
  app/routes.js
  package.json
  packages/component-submission/client/index.js
  packages/component-submission/client/pages/DetailsStepPage.js
  packages/component-submission/client/pages/NewSubmissionWizard.js
  packages/component-submission/client/pages/SubmissionWizard.js
  packages/component-submission/client/pages/SubmissionWizard.test.js
  packages/component-submission/client/utils/parseInputToFormData.js
  yarn.lock
Labels: Andon

#2101 Documentation for Server Side code guidelines
  docs/developing/server-side.md
Labels: Documentation
